FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build

WORKDIR /src

COPY . .

RUN dotnet restore ./Br.DollarQuotation.Worker/Br.DollarQuotation.Worker.csproj

RUN dotnet publish ./Br.DollarQuotation.Worker/Br.DollarQuotation.Worker.csproj -c Release -o /app/publish --no-restore

FROM mcr.microsoft.com/dotnet/runtime:9.0 AS final

WORKDIR /app

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "Br.DollarQuotation.Worker.dll"]