# ============================================================
# STAGE 1 - BUILD
# ============================================================

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build

WORKDIR /src

COPY . .

RUN dotnet restore \
    ./Br.DollarQuotation.API/Br.DollarQuotation.API.csproj

RUN dotnet publish \
    ./Br.DollarQuotation.API/Br.DollarQuotation.API.csproj \
    -c Release \
    -o /app/publish \
    --no-restore


# ============================================================
# STAGE 2 - RUNTIME
# ============================================================

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final

USER root

# ============================================================
# DEPENDÊNCIAS DO CONTAINER
# ============================================================

RUN apt-get update \
    && apt-get install -y \
        --no-install-recommends \
        ca-certificates \
        wget \
    && rm -rf /var/lib/apt/lists/*

# ============================================================
# CERTIFICADO LOCAL - AVAST
# ============================================================
#
# Necessário no ambiente local quando
# existe inspeção SSL/TLS pelo Avast.
#

COPY ./certs/avast-root.crt \
    /usr/local/share/ca-certificates/avast-root.crt

RUN update-ca-certificates

# ============================================================
# APLICAÇÃO
# ============================================================

WORKDIR /app

COPY --from=build \
    /app/publish \
    .

# ============================================================
# ASP.NET CORE
# ============================================================

ENV ASPNETCORE_URLS=http://+:8080

ENV DOTNET_RUNNING_IN_CONTAINER=true

EXPOSE 8080

# ============================================================
# INICIALIZAÇÃO
# ============================================================

ENTRYPOINT ["dotnet", "Br.DollarQuotation.API.dll"]