// <auto-generated />
using System;
using Br.DollarQuotation.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Br.DollarQuotation.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260811220830_RemoveUserRoleDefault")]
    partial class RemoveUserRoleDefault
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Br.DollarQuotation.Domain.Entities.CurrencyQuotation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AskPrice")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("ask_price");

                    b.Property<decimal>("BidPrice")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("bid_price");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrencyPair")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("currency_pair");

                    b.Property<decimal>("HighPrice")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("high_price");

                    b.Property<decimal>("LowPrice")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("low_price");

                    b.Property<DateTime>("QuotationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("quotation_date");

                    b.Property<decimal>("Variation")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("variation");

                    b.Property<decimal>("VariationPercentage")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("variation_percentage");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyPair")
                        .HasDatabaseName("ix_currency_quotations_currency_pair");

                    b.HasIndex("QuotationDate")
                        .HasDatabaseName("ix_currency_quotations_quotation_date");

                    b.HasIndex("CurrencyPair", "QuotationDate")
                        .IsUnique()
                        .HasDatabaseName("ux_currency_quotations_pair_date");

                    b.ToTable("currency_quotations", (string)null);
                });

            modelBuilder.Entity("Br.DollarQuotation.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_password_reset_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_password_reset_tokens_user_id");

                    b.HasIndex("UserId", "ExpiresAt", "UsedAt")
                        .HasDatabaseName("ix_password_reset_tokens_user_status");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("Br.DollarQuotation.Domain.Entities.QuotationAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Condition")
                        .HasColumnType("integer")
                        .HasColumnName("condition");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrencyPair")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("currency_pair");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal>("TargetPrice")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("target_price");

                    b.Property<DateTime?>("TriggeredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("triggered_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyPair")
                        .HasDatabaseName("ix_quotation_alerts_currency_pair");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_quotation_alerts_is_active");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_quotation_alerts_user_id");

                    b.HasIndex("UserId", "CurrencyPair", "IsActive")
                        .HasDatabaseName("ix_quotation_alerts_user_pair_active");

                    b.ToTable("quotation_alerts", (string)null);
                });

            modelBuilder.Entity("Br.DollarQuotation.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhotoBase64")
                        .HasColumnType("text")
                        .HasColumnName("photo_base64");

                    b.Property<string>("PhotoContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("photo_content_type");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Br.DollarQuotation.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("Br.DollarQuotation.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Br.DollarQuotation.Domain.Entities.QuotationAlert", b =>
                {
                    b.HasOne("Br.DollarQuotation.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
