<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>d1a7fd35-029d-45d1-8b23-78adf1a71416</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.NpgSql" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.18" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.18">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Br.DollarQuotation.Application\Br.DollarQuotation.Application.csproj" />
    <ProjectReference Include="..\Br.DollarQuotation.CrossCutting\Br.DollarQuotation.CrossCutting.csproj" />
    <ProjectReference Include="..\Br.DollarQuotation.Domain\Br.DollarQuotation.Domain.csproj" />
  </ItemGroup>

</Project>
